server:
  port: 8080



spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.5:3306/bdp_sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
