server:
  port: 8080



spring:
  cache:
    type: redis
  redis:
    #数据库索引
    database: 1
    host: 192.168.15.5
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 500
        max-wait: -1s
        #最大阻塞等待时间(负数表示没限制)
        #最大空闲
        max-idle: 100
        #最小空闲
        min-idle: 10
    timeout: 10s
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.15.5:3306/bdp_sys?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
